### ISSUE TITLE
Always Encrypted DateTime2/Date/DateTime issue

### ISSUE THREAD

**Issue by Jetski5822** [dallasbeek/Dapper.Database#26]
So say you have a Schema

Employees
 - DateofBirth (Date) (Encrypted ENCRYPTION_TYPE = DETERMINISTIC)
 - ModifiedUtc (DateTime2)

When you go to do an insert against Employees, you will get;

 ```
Tesco.HRAM.Tests.Ingestion.ContractualShiftChangeTests.Generation_of_next_weeks_shifts_should_use_last_contractual
   Source: ContractualShiftChangeTests.cs line 127
   Duration: 1.1 sec

  Message: 
    Assert.Null() Failure
    Expected: (null)
    Actual:   Microsoft.Data.SqlClient.SqlException (0x80131904): Operand type clash: datetime2(7) encrypted with (encryption_type = 'DETERMINISTIC', encryption_algorithm_name = 'AEAD_AES_256_CBC_HMAC_SHA_256', column_encryption_key_name = 'AlwaysEncryptedCEK', column_encryption_key_database_name = '_obdkhjyvqu') is incompatible with date encrypted with (encryption_type = 'DETERMINISTIC', encryption_algorithm_name = 'AEAD_AES_256_CBC_HMAC_SHA_256', column_encryption_key_name = 'AlwaysEncryptedCEK', column_encryption_key_database_name = '_obdkhjyvqu')
    Statement(s) could not be prepared.
       at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
       at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
    --- End of stack trace from previous location where exception was thrown ---
       at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in /_/Dapper/SqlMapper.Async.cs:line 678
       at Dapper.Database.Adapters.SqlServerAdapter.InsertAsync[T](IDbConnection connection, IDbTransaction transaction, Nullable`1 commandTimeout, TableInfo tableInfo, T entityToInsert) in C:\projects\dapper-database\Dapper.Database\Adapters\SqlServerAdapter.cs:line 88
       at Dapper.Database.Adapters.SqlAdapter.UpsertAsync[T](IDbConnection connection, IDbTransaction transaction, Nullable`1 commandTimeout, TableInfo tableInfo, T entityToUpsert, IEnumerable`1 columnsToUpdate, Action`1 insertAction, Action`1 updateAction) in C:\projects\dapper-database\Dapper.Database\Adapters\SqlAdapter.cs:line 694
       at Dapper.Database.Extensions.SqlMapperExtensions.UpsertAsync[T](IDbConnection connection, T entityToUpsert, IEnumerable`1 columnsToUpdate, Action`1 insertAction, Action`1 updateAction, IDbTransaction transaction, Nullable`1 commandTimeout) in C:\projects\dapper-database\Dapper.Database\Extensions\SqlUpsertExtensions.cs:line 144
       at Dapper.Database.Extensions.SqlMapperExtensions.UpsertAsync[T](IDbConnection connection, T entityToUpsert, Action`1 insertAction, Action`1 updateAction, IDbTransaction transaction, Nullable`1 commandTimeout) in C:\projects\dapper-database\Dapper.Database\Extensions\SqlUpsertExtensions.cs:line 124
       at Tesco.HRAM.Data.Services.EmployeeRepository.UpsertAsync(Int32 employeeId, Action`1 mapInsert, Action`1 mapUpdate, IDbTransaction transaction) in C:\projects\HRAM\src\Tesco.HRAM.Data\Services\EmployeeRepository.cs:line 136
       at Tesco.TAM.APIAdaptor.Processor.Services.Parts.EmployeePersonDetailsPartService.Upsert(Int32 employeeId, DateTime effectiveDate, Guid locationId, EmployeePersonDetailsPart employeeDetails, IDbTransaction transaction, Boolean isLeaver, Boolean isReinstatement) in C:\projects\HRAM\src\Tesco.TAM.APIAdaptor.Processor\Services\Parts\EmployeePersonDetailsPartService.cs:line 124
       at Tesco.TAM.APIAdaptor.Processor.Services.ShiftContractualService.UpsertAssignment(Guid locationId, Int32 employeeId, Boolean isWeekShift, DateTime effectiveFrom, EmployeePersonDetailsPart employeeDetails, IDbTransaction transaction) in C:\projects\HRAM\src\Tesco.TAM.APIAdaptor.Processor\Services\ShiftContractualService.cs:line 166
       at Tesco.TAM.APIAdaptor.Processor.Services.ShiftContractualService.Process(Int32 employeeId, ContentAPIShiftContractual shiftContractual, IDbTransaction transaction) in C:\projects\HRAM\src\Tesco.TAM.APIAdaptor.Processor\Services\ShiftContractualService.cs:line 109
       at Tesco.TAM.APIAdaptor.Processor.Tasks.ContentAPIColleagueProcessorTask.ProcessRecord(Int32 employeeId, HRAMAdaptorRecord record, IDbTransaction transaction) in C:\projects\HRAM\src\Tesco.TAM.APIAdaptor.Processor\Tasks\ContentAPIColleagueProcessorTask.cs:line 152
       at Tesco.TAM.APIAdaptor.Processor.Tasks.ContentAPIColleagueProcessorTask.Execute(Location location) in C:\projects\HRAM\src\Tesco.TAM.APIAdaptor.Processor\Tasks\ContentAPIColleagueProcessorTask.cs:line 106
    ClientConnectionId:83fe445d-0793-4dfc-b72e-7f55865d7bda
    Error Number:206,State:2,Class:16
  Stack Trace: 
    ContractualShiftChangeTests.IngestRecord(TescoCalendar now, String contentType, ContentApi content, DateTime effectiveDateTime) line 421
    ContractualShiftChangeTests.CreateShift(TescoCalendar now, DateTime validFrom, DateTime validTo, ShiftContractualDetail shift) line 444
    ContractualShiftChangeTests.Generation_of_next_weeks_shifts_should_use_last_contractual() line 136
    --- End of stack trace from previous location where exception was thrown ---
```

the Column Attribute takes TypeName, but it appears that we ignore it in this lib, any thoughts?

**Comment by dallasbeek** [comment]
I let dapper handle most of the type mappings.  I think there are possibly 2 different things here.  

The first is I think you need to register datetime2 with Dapper.  I think this line of code will globally map DateTime to database DateTime2.  

`SqlMapper.AddTypeMap(typeof(DateTime), DbType.DateTime2);`

See this article https://dapper-tutorial.net/knowledge-base/51879979/changing-the-dapper-mapping-for--net-datetime-to-use-dbtype-datetime2-and-reinstating-it-back-again

Try adding the above line and see if it works but if not the second issue I think you will have is that the column is always encrypted and I'm not sure Dapper handles that as I haven't worked with it. From what I see for a decimal column is it requires adding parameters with precision and scale.
`dynamicParameters.Add("Salary", 300, DbType.Decimal, precision: 11, scale: 3);`

I should have some time this weekend to test this out.

**Comment by Jetski5822** [comment]
Hey - thanks for the heads up with setting and un-setting;

We have quite alot of dapper code, and im not how this would handle under load if you keep setting and and un-setting it.

Could we not make the SQL Builder take in to account the type from the ColumnAttribute?

**Comment by dallasbeek** [comment]
I spent a number of hours looking at this. I have several ideas including using your idea of TypeName property in the column. To do that would require parsing the entity into dynamic parameters and instead of passing the entity to Dapper I'd pass the properties. I'd like to avoid that. I'm now looking at the Dapper code to determine if there are other ways. Another possibility is to create your own DateTime2 .net class and register that as a global mapper. There just isn't a great way to tell Dapper to handle this DateTime property differently than this other DateTime property.

**Comment by dallasbeek** [comment]
Quick question, you have both datetime and datetime2 columns right?

**Comment by Jetski5822** [comment]
Hey - nice one;

>you have both datetime and datetime2 columns right?

Yeah, but more Date/Time and DateTime2

**Comment by dallasbeek** [comment]
So long story short the issue is that dapper maps .Net types to Database types and doesn't have a way to override mappings on a per query basis. I don't feel comfortable implementing this ability in my library because it negates the purpose of using Dapper. I assume you may be migrating from datetime to datetime2 and eventually you will get all of them in your database the same. When you do you can simply do this
`SqlMapper.AddTypeMap(typeof(DateTime), DbType.DateTime2);`

Another option is to create your own .net datetime2 and map it. I've attached a test file where I was able to have both datetime and datetime2 in the same table and it worked with encryption. My DateTime2 class probably needs to implement some other stuff (IComparable, IEquatable, ISerializable etc.)  Assuming your migrating your tables this might work as a stop gap.
[DateTimeTests.txt](https://github.com/dallasbeek/Dapper.Database/files/4692439/DateTimeTests.txt)

**Comment by Jetski5822** [comment]
Hey - just wanted to say thanks for looking;

I ended moving it all over so in the end a mix wasn’t needed.. kinda wish dapper had the conversation native.

Thanks again

Nick
